### PR TITLE
Fix: Window resize issue and change quote section font

### PR DESCRIPTION
**Pull request by rowhitswami**

### CODE REVIEW

**Comment by rowhitswami** [comment]
Changed font-size and font-style of some element so that it looks better

Screenshot from 2019-10-04 20-12-21

**Comment by rowhitswami** [comment]
1. Redesigned input area with material design.
2. While editing, input field will contain the task name.
3. While editing, the task will be hidden.

Screenshot from 2019-10-05 01-27-28

**Comment by pprathameshmore** [comment]
@rowhitswami You have done great work but we have to keep this extension clean and simple. So only one thing I want to say that restoring the fonts for quotes would be better.  The input area is looking awesome. Change the blue color back to white. So it will look more clean simple.

**Comment by pprathameshmore** [comment]
@rowhitswami Try pull new changes

**Comment by pprathameshmore** [comment]
Try to keep files in local folder. Don't use external links.

**Pull request closed without merging**
